import React from "react";
import Header from "../Components/Header";
import Accordion from "../Components/Accordion";

const Experience = () => {
    const sections = [
        {
            id: "industry",
            title: "Industry Experience",
            content: (
                <div className="card-section">
                    {/* ASML Card */}
                    <div className="card-item">
                        <h3 className="card-title">ASML, Inc.</h3>
                        <h4 className="card-subtitle">
                            Mechatronics Research Engineer Intern
                        </h4>
                        <p className="card-description">
                            June 2025 - September 2025 | Wilton, CT
                        </p>
                        {/* <ul className="card-list">
                            
                        </ul> */}
                    </div>

                    {/* ASML Card */}
                    <div className="card-item">
                        <h3 className="card-title">ASML, Inc.</h3>
                        <h4 className="card-subtitle">
                            Mechatronics and Control Systems Engineer Intern
                        </h4>
                        <p className="card-description">
                            June 2024 - September 2024 | Wilton, CT
                        </p>
                        <ul className="card-list">
                            <li>
                                Developed a Gaussian Process Regression (GPR)
                                model to predict force generated by a
                                piezo-electric actuator, which led to a pending
                                patent
                            </li>
                            <li>
                                Enhanced baseline code for model training with
                                various dataset sizes and visualization tools
                            </li>
                            <li>
                                Automated a MATLAB/Python script, reducing
                                workflow from 40 hours to an overnight run
                            </li>
                            <li>
                                Investigated optimization problems and
                                current-control hardware issues for test stands
                            </li>
                            <li>
                                <strong>Tools and Skills:</strong> Python,
                                MATLAB, MS Excel, GPR, ML, convex optimization,
                                electrical circuits, Sobol space-filled design
                                of experiments, ASML machine software and
                                software processes
                            </li>
                        </ul>
                    </div>

                    {/* AviaPro Consulting Inc. Card */}
                    <div className="card-item">
                        <h3 className="card-title">AviaPro Consulting Inc.</h3>
                        <h4 className="card-subtitle">Software Developer</h4>
                        <p className="card-description">
                            June 2022 - July 2023 | Remote
                        </p>
                        <ul className="card-list">
                            <li>
                                Developed web applications and applied software
                                DevOps practices
                            </li>
                            <li>
                                Contributed to multiple full stack web
                                development projects as well as a solo full
                                stack web dev project
                            </li>
                            <li>
                                <strong>Tools and Skills:</strong> HTML, JS,
                                CSS, React.js, Node.js, Databases, Microsoft
                                Tools
                            </li>
                        </ul>
                    </div>
                </div>
            ),
        },
        {
            id: "academic",
            title: "Academic Experience",
            content: (
                <div className="card-section">
                    {/* University of California, Irvine Card */}
                    <div className="card-item">
                        <h3 className="card-title">
                            University of California, Irvine
                        </h3>
                        <h4 className="card-subtitle">
                            Graduate Student Researcher
                        </h4>
                        <p className="card-description">
                            April 2025 - June 2025 | Irvine, CA
                        </p>
                        <ul className="card-list">
                            <li>
                                Conducting research in collaborative
                                heterogenous multi-agent systems, graph neural
                                networks, and reinforcement learning
                            </li>
                            <li>
                                Working on multiple projects based on
                                collaboration in multi-agent systems, coverage
                                control, graph neural networks, and applied
                                machine learning
                            </li>
                        </ul>
                    </div>
                    {/* University of California, Irvine Card */}
                    <div className="card-item">
                        <h3 className="card-title">
                            University of California, Irvine
                        </h3>
                        <h4 className="card-subtitle">
                            Graduate Student Researcher
                        </h4>
                        <p className="card-description">
                            January 2024 - June 2024 | Irvine, CA
                        </p>
                        <ul className="card-list">
                            <li>
                                Conducting research in the field of multi-agent
                                systems, control, optimization, and ecology
                                robotics
                            </li>
                            <li>
                                Working on multiple projects based on
                                collaboration in multi-agent systems, formation
                                control, coverage control, graph neural
                                networks, applied computer vision and machine
                                learning
                            </li>
                        </ul>
                    </div>
                </div>
            ),
        },
    ];

    return (
        <div className="container home-container">
            <Header />
            <Accordion sections={sections} />
        </div>
    );
};

export default Experience;
